### ISSUE TITLE
Big up S4ND3RS with finding the game braking bugs 

### ISSUE THREAD

**Issue by 1S4ND3RS1** [Galaxy-Devhub/development#12]
**What Is The Issue?**duplicating a gun when im not trying to 

**How Do You Reproduce This Error** im not sure but im pretty sure it happend after i died and reloged 

**What Is Meant To Happen** not give me a ump 

**Screenshots/Video**

**Additional context** giving me a ump body when i equip bullets 

**Any Modified Game Fies?, Graphic Pack, Sound Packs?**

**Perm ID/Steam HEX**perm id is 25 

https://user-images.githubusercontent.com/101198221/157266331-4dfde647-c98e-4ddf-8d4e-11c460fbf194.mp4

**Comment by regiments** [comment]
Been Reported Already
