### ISSUE TITLE
Barber Shop Error 

### ISSUE THREAD

**Issue by Stark231** [Galaxy-Devhub/development#14]
**What Is The Issue?**
Error With Barber shop Also you spelt files wrong  
**How Do You Reproduce This Error**
i was in a sit can checked my F8 and saw it 
**What Is Meant To Happen**
idk
**Screenshots/Video**
![image](https://user-images.githubusercontent.com/95376921/157266337-1f1c7d56-f5c2-4d1e-8bb2-d88b1b7e7670.png)

**Additional context**

**Any Modified Game Files?, Graphic Pack, Sound Packs?**
yea tracers and a gun sound pack 
**Perm ID/Steam HEX**
17

**Comment by regiments** [comment]
its not an error really, it just happens cause of how fivem is
