### ISSUE TITLE
pd sirens arent working. apparently u need to start a script or something not sure ask dubzyy

### ISSUE THREAD

**Issue by Wellsyyy** [Galaxy-Devhub/development#20]
**What Is The Issue?**

**How Do You Reproduce This Error**

**What Is Meant To Happen**

**Screenshots/Video**

**Additional context**

**Any Modified Game Fies?, Graphic Pack, Sound Packs?**

**Perm ID/Steam HEX**

**Comment by regiments** [comment]
dubzy can fixi, he is head car dev
