### ISSUE TITLE
Loosing Armour n Guns On Relog

### ISSUE THREAD

**Issue by GDC-Customs** [Galaxy-Devhub/development#32]
**What Is The Issue?**
When relogging/leaving n rejoining, you loose all guns/cash/armour u had on you.
**How Do You Reproduce This Error**

**What Is Meant To Happen**
not loose ur shit
**Screenshots/Video**
trry it for urself
**Additional context**

**Any Modified Game Fies?, Graphic Pack, Sound Packs?**

**Perm ID/Steam HEX**
10

**Comment by regiments** [comment]
fixed
