### ISSUE TITLE
sometimes i cant pull my gun out 

### ISSUE THREAD

**Issue by pluxyy** [Galaxy-Devhub/development#9]
**What Is The Issue?**

**How Do You Reproduce This Error**

**What Is Meant To Happen**

**Screenshots/Video**

**Additional context**

**Any Modified Game Fies?, Graphic Pack, Sound Packs?**

**Perm ID/Steam HEX**

**Comment by regiments** [comment]
Need More Info And a clip please

**Comment by regiments** [comment]
Fixed
